### ISSUE TITLE
10.3 firmware update has rendered screen unuseable

### ISSUE THREAD

**Issue by jarrodthebobo** [eleclab-rpi/Display_Firmware#1]
Hello, I've flashed my screen (10.3 1280x800) with the new firmware made available here and it no longer is showing picture on any of my devices I have tried it with. HDMI Signal APPEARS to be detected since the light will go green on the screen, but no picture will show besides the backlight turning on.

Additionally, I tried the "np swap) firmware variant which also appears non functional.

**Comment by eleclab-rpi** [comment]
Sorry, do you have a 10.1" 1280x800 display or a 10.3" 1280x480 display?
The corresponding relationship between the display screen and firmware is:
7.4” 1280x400 -->HDMI_0736_1280x400.hex
8.0" 1024x600 -->HDMI_080_1024x600.hex
8.0" 1280x720 -->HDMI_080_1280x720.hex
10.1" 1280x800 -->HDMI_101_1280x800_NP_SWAP.hex
10.3" 1280x480 -->HDMI_103_1280x480.hex

If the green light turns on, it means that the display has recognized the HDMI signal. Are you using a Raspberry Pi or an X86 PC to connect the display?



***@***.***
 
From: jarrodthebobo
Date: 2023-10-22 09:22
To: eleclab-rpi/Display_Firmware
CC: Subscribed
Subject: [eleclab-rpi/Display_Firmware] 10.3 firmware update has rendered screen unuseable (Issue #1)
Hello, I've flashed my screen (10.3 1280x800) with the new firmware made available here and it no longer is showing picture on any of my devices I have tried it with. HDMI Signal APPEARS to be detected since the light will go green on the screen, but no picture will show besides the backlight turning on.
Additionally, I tried the "np swap) firmware variant which also appears non functional.

**Comment by jarrodthebobo** [comment]
Apologies: it's the 10.1" screen. 

I've tried using the screen with both a windows x86 based laptop and a Radxa rock 5b. 

HDMI_101_1280x800_NP_SWAP.hex vs HDMI_101_1280x800.hex ... what's the difference between these two?

**Comment by eleclab-rpi** [comment]
NP_SWAP is the firmware in use, and the other one is for R&D testing. Does the backlight of the screen turn on on the X86? If possible, please take a photo of the back so that we can more easily determine the problem, because there are 2 models of LCD screens, and they use different FPC cables to connect to the PCB of the display.



***@***.***
 
From: jarrodthebobo
Date: 2023-10-22 21:02
To: eleclab-rpi/Display_Firmware
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/Display_Firmware] 10.3 firmware update has rendered screen unuseable (Issue #1)
Apologies: it's the 10.1" screen.
I've tried using the screen with both a windows x86 based laptop and a Radxa rock 5b.
HDMI_101_1280x800_NP_SWAP.hex vs HDMI_101_1280x800.hex ... what's the difference between these two?

**Comment by jarrodthebobo** [comment]
Hello,

Good news is that after using the NP_SWAP variant (for the 3rd time), it appears to be functional now across both the X86 and ARM64 platforms. I'm starting to wonder if the usb c cable I'd been using is intermittently losing connection and is having issues writing the hex file to the controller.

Thanks for the clarification/help though!

**Comment by eleclab-rpi** [comment]
That’s great news, and we’re going to continue to analyze the possibility of the problem in depth.
You're welcome and any ideas are welcome.



***@***.***
 
From: jarrodthebobo
Date: 2023-10-22 21:48
To: eleclab-rpi/Display_Firmware
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/Display_Firmware] 10.3 firmware update has rendered screen unuseable (Issue #1)
Hello,
Good news is that after using the NP_SWAP variant (for the 3rd time), it appears to be functional now across both the X86 and ARM64 platforms. I'm starting to wonder if the usb c cable I'd been using is intermittently losing connection and is having issues writing the hex file to the controller.
Thanks for the clarification/help though!
